server:
  port: 8081

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/storedb
    username: testuser
    password: Somepostgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

jwt:
  secret: oXfoTNh5L3vrONyHrSFaL+WGWB/8S908Qf1TpakPvkA=
  access-token-expiration: 900000 #15 minutes
  refresh-token-expiration: 604800000 # 7 days
  access-cookie-name: my_access_token_cookie
  refresh-cookie-name: my_refresh_token_cookie

logging:
  level:
    org.springframework.security: DEBUG

app:
  bootstrap-users:
    - name: "Admin"
      email: "admin@example.com"
      password: "admin123"
      roles:
        - ADMIN
        - MANAGER
        - STAFF

    - name: "Manager"
      email: "manager@example.com"
      password: "manager123"
      roles:
        - MANAGER
        - STAFF

    - name: "User"
      email: "user@example.com"
      password: "user123"
      roles:
        - STAFF
